# This FUNDING.yml file is used by GitHub to show funding links on your repository

# github: [techdebtgpt]  # GitHub Sponsors
# patreon: techdebtgpt
# open_collective: techdebtgpt
# ko_fi: techdebtgpt
# tidelift: npm/@techdebtgpt/archdoc-generator
# custom: ["https://techdebtgpt.com/sponsor", "https://techdebtgpt.com/donate"]
