import * as fs from 'fs/promises';
import * as path from 'path';
import type { C4ModelOutput } from '../orchestrator/c4-model-orchestrator';

export interface C4ModelFormatterOptions {
  outputDir: string;
}

/**
 * Formatter for C4 Model documentation
 * Generates markdown files from C4ModelOutput
 */
export class C4ModelFormatter {
  async format(output: C4ModelOutput, options: C4ModelFormatterOptions): Promise<void> {
    const { outputDir } = options;

    // Ensure output directory exists
    await fs.mkdir(outputDir, { recursive: true });

    // Generate all markdown files and PlantUML diagrams
    await Promise.all([
      this.writeIndexFile(output, outputDir),
      this.writeMetadataFile(output, outputDir),
      this.writeContextFile(output, outputDir),
      this.writeContainersFile(output, outputDir),
      this.writeComponentsFile(output, outputDir),
      this.writeRecommendationsFile(output, outputDir),
      this.writeChangelogFile(output, outputDir),
      this.writePlantUMLFiles(output, outputDir),
    ]);
  }

  private async writeIndexFile(output: C4ModelOutput, outputDir: string): Promise<void> {
    const content = `# C4 Architecture Model - ${output.projectName}

> Generated on ${output.timestamp.toLocaleString()}

## Overview

This documentation contains the C4 architecture model for ${output.projectName}, providing multiple views of the system at different levels of abstraction.

## 📚 Documentation Structure

### Architecture Diagrams

- **[Context Diagram](./c4-context.md)** - System context showing actors and external systems
- **[Containers Diagram](./c4-containers.md)** - High-level technology choices and containers
- **[Components Diagram](./c4-components.md)** - Internal components and their relationships

### Additional Resources

- **[Recommendations](./recommendations.md)** - Architecture improvement suggestions
- **[Metadata](./metadata.md)** - Generation details and statistics
- **[Changelog](./changelog.md)** - Documentation update history

## 🎯 Quick Start

1. Start with the [Context Diagram](./c4-context.md) to understand the system boundary
2. Explore the [Containers Diagram](./c4-containers.md) to see high-level architecture
3. Dive into the [Components Diagram](./c4-components.md) for detailed internal structure
4. Review [Recommendations](./recommendations.md) for improvement opportunities

## 📊 PlantUML Diagrams

The following PlantUML files can be rendered visually:

- \`context.puml\` - Context diagram source
- \`containers.puml\` - Containers diagram source
- \`components.puml\` - Components diagram source

Use PlantUML to generate SVG/PNG diagrams from these files.

---

*Generated by ArchDoc C4 Model Generator*
`;

    await fs.writeFile(path.join(outputDir, 'index.md'), content, 'utf-8');
  }

  private async writeMetadataFile(output: C4ModelOutput, outputDir: string): Promise<void> {
    const content = `# Generation Metadata

## Project Information

- **Project Name**: ${output.projectName}
- **Generated At**: ${output.timestamp.toISOString()}
- **Generation Time**: ${(output.metadata.generationDuration / 1000).toFixed(1)}s

## Scan Results

- **Total Files**: ${output.metadata.totalFiles}
- **Total Directories**: ${output.metadata.totalDirectories}
- **Total Size**: ${((output.scanResult?.totalSize || 0) / 1024 / 1024).toFixed(2)} MB

## Language Distribution

${
  output.scanResult?.languages
    ?.map(
      (lang) => `- **${lang.language}**: ${lang.fileCount} files (${lang.percentage.toFixed(1)}%)`,
    )
    .join('\n') || 'No languages detected'
}

## Agents Executed

${output.metadata.agentsExecuted.map((name, idx) => `${idx + 1}. ${name}`).join('\n') || 'No agents executed'}

## Configuration

- **Max Tokens**: 100,000
- **Token Budget**: Unlimited
- **Parallel Execution**: Disabled (sequential for C4 model)

---

*Last updated: ${output.timestamp.toLocaleString()}*
`;

    await fs.writeFile(path.join(outputDir, 'metadata.md'), content, 'utf-8');
  }

  private async writeContextFile(output: C4ModelOutput, outputDir: string): Promise<void> {
    if (!output.c4Model?.context || !output.c4Model.context.system) {
      return; // Skip if no context data
    }

    const { context } = output.c4Model;
    const plantUML = output.plantUMLModel?.context || '';

    const content = `# C4 Context Diagram

## System Overview

### Main System

**${context.system?.name || 'Unknown System'}**

${context.system?.description || 'No description available'}

## Actors

${
  context.actors
    ?.map(
      (actor: any) => `### ${actor.name}

${actor.description}
`,
    )
    .join('\n') || '*No actors identified*'
}

## External Systems

${
  context.externalSystems
    ?.map(
      (system: any) => `### ${system.name}

${system.description}
`,
    )
    .join('\n') || '*No external systems identified*'
}

## Relationships

${
  context.relationships
    ?.map((rel: any) => `- **${rel.source}** → **${rel.destination}**: ${rel.description}`)
    .join('\n') || '*No relationships defined*'
}

${
  plantUML
    ? `
## PlantUML Diagram

\`\`\`plantuml
${plantUML}
\`\`\`

*Tip: Render this diagram using PlantUML for visualization*
`
    : ''
}

---

[← Back to Index](./index.md) | [Next: Containers →](./c4-containers.md)
`;

    await fs.writeFile(path.join(outputDir, 'c4-context.md'), content, 'utf-8');
  }

  private async writeContainersFile(output: C4ModelOutput, outputDir: string): Promise<void> {
    if (!output.c4Model?.containers || !output.c4Model.containers.containers?.length) {
      return; // Skip if no containers data
    }

    const { containers } = output.c4Model;
    const plantUML = output.plantUMLModel?.containers || '';

    const content = `# C4 Containers Diagram

## Containers

${
  containers.containers
    ?.map(
      (container: any) => `### ${container.name}

- **Technology**: ${container.technology}
- **Description**: ${container.description}
`,
    )
    .join('\n') || '*No containers identified*'
}

## Container Relationships

${
  containers.relationships
    ?.map(
      (rel: any) =>
        `- **${rel.source}** → **${rel.destination}**
  - Protocol: ${rel.technology || 'N/A'}
  - Description: ${rel.description}`,
    )
    .join('\n\n') || '*No relationships defined*'
}

${
  plantUML
    ? `
## PlantUML Diagram

\`\`\`plantuml
${plantUML}
\`\`\`

*Tip: Render this diagram using PlantUML for visualization*
`
    : ''
}

---

[← Previous: Context](./c4-context.md) | [Back to Index](./index.md) | [Next: Components →](./c4-components.md)
`;

    await fs.writeFile(path.join(outputDir, 'c4-containers.md'), content, 'utf-8');
  }

  private async writeComponentsFile(output: C4ModelOutput, outputDir: string): Promise<void> {
    if (!output.c4Model?.components || !output.c4Model.components.components?.length) {
      return; // Skip if no components data
    }

    const { components } = output.c4Model;
    const plantUML = output.plantUMLModel?.components || '';

    const content = `# C4 Components Diagram

## Container: ${components.containerName || 'Unknown Container'}

### Components

${
  components.components
    ?.map(
      (component: any) => `#### ${component.name}

${component.description}
`,
    )
    .join('\n') || '*No components identified*'
}

## Component Relationships

${
  components.relationships
    ?.map((rel: any) => `- **${rel.source}** → **${rel.destination}**: ${rel.description}`)
    .join('\n') || '*No relationships defined*'
}

${
  plantUML
    ? `
## PlantUML Diagram

\`\`\`plantuml
${plantUML}
\`\`\`

*Tip: Render this diagram using PlantUML for visualization*
`
    : ''
}

---

[← Previous: Containers](./c4-containers.md) | [Back to Index](./index.md)
`;

    await fs.writeFile(path.join(outputDir, 'c4-components.md'), content, 'utf-8');
  }

  private async writeRecommendationsFile(output: C4ModelOutput, outputDir: string): Promise<void> {
    const content = `# Architecture Recommendations

## Overview

Based on the C4 model analysis, here are recommendations for improving your architecture.

## Key Recommendations

### 1. Documentation

- ✅ **Complete**: C4 model generated successfully
- 💡 **Suggestion**: Keep diagrams updated as architecture evolves
- 💡 **Suggestion**: Consider adding ADRs (Architecture Decision Records)

### 2. Architecture Patterns

${
  output.agentResults?.has('pattern-detector')
    ? `Detected patterns: ${output.agentResults.get('pattern-detector')?.summary || 'See pattern analysis'}`
    : '- Review the architecture for common design patterns'
}

### 3. Dependencies

${
  output.agentResults?.has('dependency-analyzer')
    ? `Dependency analysis: ${output.agentResults.get('dependency-analyzer')?.summary || 'See dependency analysis'}`
    : '- Analyze external dependencies and their impact'
}

### 4. Security

${
  output.agentResults?.has('security-analyzer')
    ? `Security findings: ${output.agentResults.get('security-analyzer')?.summary || 'See security analysis'}`
    : '- Conduct security review of architecture decisions'
}

## Next Steps

1. Review each C4 diagram level for accuracy
2. Validate component boundaries and responsibilities
3. Document key architecture decisions
4. Plan for scalability and maintainability
5. Establish architecture governance processes

---

*Last updated: ${new Date().toLocaleString()}*

[← Back to Index](./index.md)
`;

    await fs.writeFile(path.join(outputDir, 'recommendations.md'), content, 'utf-8');
  }

  private async writeChangelogFile(output: C4ModelOutput, outputDir: string): Promise<void> {
    const content = `# Changelog

## ${output.timestamp.toISOString().split('T')[0]}

### Initial Generation

- ✨ Generated C4 architecture model
- 📊 Created Context, Containers, and Components diagrams
- 📝 Generated PlantUML sources
- 💡 Added architecture recommendations

---

*Generated at: ${output.timestamp.toISOString()}*

[← Back to Index](./index.md)
`;

    await fs.writeFile(path.join(outputDir, 'changelog.md'), content, 'utf-8');
  }

  private async writePlantUMLFiles(output: C4ModelOutput, outputDir: string): Promise<void> {
    await Promise.all([
      fs.writeFile(path.join(outputDir, 'context.puml'), output.plantUMLModel.context, 'utf-8'),
      fs.writeFile(
        path.join(outputDir, 'containers.puml'),
        output.plantUMLModel.containers,
        'utf-8',
      ),
      fs.writeFile(
        path.join(outputDir, 'components.puml'),
        output.plantUMLModel.components,
        'utf-8',
      ),
    ]);
  }
}
